In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn as sk

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [4]:
df = pd.read_csv("insurance.csv")
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [5]:
df.shape

(1338, 7)

In [6]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [7]:
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

### Кодирование категориальных признаков

In [8]:
df =  pd.get_dummies(df, drop_first=True)

In [9]:
df

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,True,False,True,False,False
1334,18,31.920,0,2205.98080,False,False,False,False,False
1335,18,36.850,0,1629.83350,False,False,False,True,False
1336,21,25.800,0,2007.94500,False,False,False,False,True
1337,61,29.070,0,29141.36030,False,True,True,False,False

### Разделение на признаков от цели и Тренировочную на тестовую

In [10]:
X = df.drop('charges', axis=1)
y = df['charges']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y ,test_size=0.2, random_state=42
)

print(f"Размер обучающей выборки: {X_train.shape}")
print(f"Размер тестовой выборки: {X_test.shape}")

Размер обучающей выборки: (1070, 8)
Размер тестовой выборки: (268, 8)

### Стандартизация

In [12]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Обучение на моделях машинного обучения

## Линейная регрессия

In [13]:
lr_model = LinearRegression()
lr_model.fit(X_train_scaled, y_train)

y_pred_lr = lr_model.predict(X_test_scaled)

mse_lr = mean_squared_error(y_test, y_pred_lr)
mae_lr = mean_absolute_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print(f"Среднеквадратичная ошибка (MSE): {mse_lr:.4f}")
print(f"Среднеабсолютная ошибка (MAE): {mae_lr}")
print(f"Коэффициент детерминации (R²): {r2_lr:.4f}")

Среднеквадратичная ошибка (MSE): 33596915.8514
Среднеабсолютная ошибка (MAE): 4181.194473753654
Коэффициент детерминации (R²): 0.7836

## Полиномиальная регрессия

In [14]:
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train_scaled)
X_test_poly = poly.transform(X_test_scaled)

poly_model = LinearRegression()
poly_model.fit(X_train_poly, y_train)

y_pred_poly = poly_model.predict(X_test_poly)

mse_poly = mean_squared_error(y_test, y_pred_poly)
mae_poly = mean_absolute_error(y_test, y_pred_poly)
r2_poly = r2_score(y_test, y_pred_poly)

print(f"Среднеквадратичная ошибка (MSE): {mse_poly:.4f}")
print(f"Среднеабсолютная ошибка (MAE): {mae_poly}")
print(f"Коэффициент детерминации (R²): {r2_poly:.4f}")

Среднеквадратичная ошибка (MSE): 20712805.9879
Среднеабсолютная ошибка (MAE): 2729.5001336394525
Коэффициент детерминации (R²): 0.8666

## Деревья решений

In [15]:
dt_model = DecisionTreeRegressor(
    max_depth=10,           # Максимальная глубина дерева
    min_samples_split=20,   # Минимальное количество образцов для разделения узла
    min_samples_leaf=10,    # Минимальное количество образцов в листе
    random_state=42
)

dt_model.fit(X_train_scaled, y_train)

y_pred_dt = dt_model.predict(X_test_scaled)

mse_dt = mean_squared_error(y_test, y_pred_dt)
mae_dt = mean_absolute_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print(f"Среднеквадратичная ошибка (MSE): {mse_dt:.4f}")
print(f"Среднеабсолютная ошибка (MAE): {mae_dt:.4f}")
print(f"Коэффициент детерминации (R²): {r2_dt:.4f}")

Среднеквадратичная ошибка (MSE): 22637166.0979
Среднеабсолютная ошибка (MAE): 2751.7451
Коэффициент детерминации (R²): 0.8542

## Случайный лес

In [ ]:
rf_model = RandomForestRegressor(
    n_estimators=100,       # Количество деревьев
    max_depth=None,         # Максимальная глубина (None - без ограничения)
    random_state=42
)

rf_model.fit(X_train_scaled, y_train)

y_pred_rf = rf_model.predict(X_test_scaled)

mse_rf = mean_squared_error(y_test, y_pred_rf)
mae_rf = mean_absolute_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print(f"Среднеквадратичная ошибка (MSE): {mse_rf:.4f}")
print(f"Среднеабсолютная ошибка (MAE): {mae_rf:.4f}")
print(f"Коэффициент детерминации (R²): {r2_rf:.4f}")

## Градиентный бустинг

In [16]:
from catboost import CatBoostRegressor
import xgboost as xgb
import lightgbm as lgb

### CatBoost

In [22]:
model_cat = CatBoostRegressor(
    iterations=500, 
    learning_rate=0.5, 
    depth=6
)

model_cat.fit(X_train_scaled, y_train, eval_set=(X_test_scaled, y_test))

predications_cat = model_cat.predict(X_test_scaled)

mse_cat = mean_squared_error(y_test, predications_cat)
mae_cat = mean_absolute_error(y_test, predications_cat)
r2_cat = r2_score(y_test, predications_cat)

print(f"Среднеквадратичная ошибка (MSE): {mse_cat:.4f}")
print(f"Среднеабсолютная ошибка (MAE): {mae_cat:.4f}")
print(f"Коэффициент детерминации (R²): {r2_cat:.4f}")

0:	learn: 7571.2270970	test: 7719.2213348	best: 7719.2213348 (0)	total: 966us	remaining: 482ms
1:	learn: 5709.3050160	test: 5696.0780986	best: 5696.0780986 (1)	total: 1.92ms	remaining: 478ms
2:	learn: 5055.2533878	test: 4955.1178825	best: 4955.1178825 (2)	total: 3.13ms	remaining: 518ms
3:	learn: 4711.6873069	test: 4589.8479339	best: 4589.8479339 (3)	total: 4.32ms	remaining: 535ms
4:	learn: 4535.4819623	test: 4400.7946600	best: 4400.7946600 (4)	total: 5.47ms	remaining: 541ms
5:	learn: 4432.5048360	test: 4359.2620139	best: 4359.2620139 (5)	total: 6.73ms	remaining: 555ms
6:	learn: 4391.9380656	test: 4347.2675501	best: 4347.2675501 (6)	total: 7.79ms	remaining: 549ms
7:	learn: 4353.7614025	test: 4354.1050058	best: 4347.2675501 (6)	total: 8.9ms	remaining: 547ms
8:	learn: 4324.4234456	test: 4352.2639390	best: 4347.2675501 (6)	total: 10ms	remaining: 546ms
9:	learn: 4278.6752658	test: 4313.3192570	best: 4313.3192570 (9)	total: 11ms	remaining: 539ms
10:	learn: 4248.7429464	test: 4309.1571437	best: 4309.1571437 (10)	total: 12.1ms	remaining: 537ms
11:	learn: 4157.0264347	test: 4359.1629181	best: 4309.1571437 (10)	total: 13.2ms	remaining: 537ms
12:	learn: 4091.8060166	test: 4391.7714985	best: 4309.1571437 (10)	total: 14.3ms	remaining: 537ms
13:	learn: 4059.8651479	test: 4398.2703962	best: 4309.1571437 (10)	total: 15.4ms	remaining: 536ms
14:	learn: 4055.0995520	test: 4397.4835782	best: 4309.1571437 (10)	total: 16ms	remaining: 516ms
15:	learn: 4030.4745765	test: 4408.2111030	best: 4309.1571437 (10)	total: 17.1ms	remaining: 517ms
16:	learn: 3969.9524189	test: 4416.2547407	best: 4309.1571437 (10)	total: 18.2ms	remaining: 517ms
17:	learn: 3936.0731409	test: 4414.3655913	best: 4309.1571437 (10)	total: 19.3ms	remaining: 518ms
18:	learn: 3877.0757362	test: 4389.2201241	best: 4309.1571437 (10)	total: 20.5ms	remaining: 520ms
19:	learn: 3832.7974268	test: 4408.6511395	best: 4309.1571437 (10)	total: 21.7ms	remaining: 521ms
20:	learn: 3807.2653982	test: 4400.8426097	best: 4309.1571437 (10)	total: 22.8ms	remaining: 520ms
21:	learn: 3787.8304668	test: 4403.2840324	best: 4309.1571437 (10)	total: 24ms	remaining: 521ms
22:	learn: 3772.7239208	test: 4404.1921868	best: 4309.1571437 (10)	total: 25.1ms	remaining: 520ms
23:	learn: 3752.9353208	test: 4403.0318342	best: 4309.1571437 (10)	total: 26.2ms	remaining: 519ms
24:	learn: 3736.4198662	test: 4424.8995532	best: 4309.1571437 (10)	total: 27.2ms	remaining: 517ms
25:	learn: 3697.9500972	test: 4418.5051166	best: 4309.1571437 (10)	total: 28.3ms	remaining: 516ms
26:	learn: 3657.5156254	test: 4400.9360353	best: 4309.1571437 (10)	total: 29.3ms	remaining: 514ms
27:	learn: 3635.2092320	test: 4434.9700284	best: 4309.1571437 (10)	total: 35.1ms	remaining: 591ms
28:	learn: 3605.7104329	test: 4438.8316388	best: 4309.1571437 (10)	total: 38.2ms	remaining: 620ms
29:	learn: 3598.8942932	test: 4432.9448121	best: 4309.1571437 (10)	total: 41.1ms	remaining: 644ms
30:	learn: 3582.8253590	test: 4451.0834235	best: 4309.1571437 (10)	total: 42.5ms	remaining: 642ms
31:	learn: 3568.9180279	test: 4446.6365489	best: 4309.1571437 (10)	total: 44.2ms	remaining: 647ms
32:	learn: 3534.0985159	test: 4474.4253614	best: 4309.1571437 (10)	total: 46.2ms	remaining: 654ms
33:	learn: 3505.9232565	test: 4490.8640358	best: 4309.1571437 (10)	total: 47.6ms	remaining: 652ms
34:	learn: 3496.5361078	test: 4495.6673286	best: 4309.1571437 (10)	total: 49ms	remaining: 650ms
35:	learn: 3473.3165639	test: 4477.4152567	best: 4309.1571437 (10)	total: 50.1ms	remaining: 646ms
36:	learn: 3452.1907125	test: 4514.7860902	best: 4309.1571437 (10)	total: 51.4ms	remaining: 643ms
37:	learn: 3415.8497627	test: 4512.3057835	best: 4309.1571437 (10)	total: 52.5ms	remaining: 639ms
38:	learn: 3389.5820776	test: 4502.6321546	best: 4309.1571437 (10)	total: 53.6ms	remaining: 633ms
39:	learn: 3385.9007437	test: 4496.3085356	best: 4309.1571437 (10)	total: 54.7ms	remaining: 629ms
40:	learn: 3369.5703371	test: 4492.7184962	best: 4309.1571437 (10)	total: 55.8ms	remaining: 624ms
41:	learn: 3340.9943610	test: 4497.6408528	best: 4309.1571437 (10)	total: 58.1ms	remaining: 634ms
42:	learn: 3318.0809329	test: 4495.4935758	best: 4309.1571437 (10)	total: 59.8ms	remaining: 635ms
43:	learn: 3287.3102598	test: 4503.3185236	best: 4309.1571437 (10)	total: 61.4ms	remaining: 637ms
44:	learn: 3260.5051975	test: 4503.7844839	best: 4309.1571437 (10)	total: 62.7ms	remaining: 634ms
45:	learn: 3254.0575156	test: 4505.4768734	best: 4309.1571437 (10)	total: 63.9ms	remaining: 631ms
46:	learn: 3251.2286647	test: 4510.4813231	best: 4309.1571437 (10)	total: 65ms	remaining: 627ms
47:	learn: 3244.9512555	test: 4507.9261815	best: 4309.1571437 (10)	total: 66.2ms	remaining: 623ms
48:	learn: 3217.7162649	test: 4510.2450055	best: 4309.1571437 (10)	total: 67.4ms	remaining: 621ms
49:	learn: 3192.4261049	test: 4500.0060696	best: 4309.1571437 (10)	total: 68.7ms	remaining: 618ms
50:	learn: 3147.4657489	test: 4496.0250753	best: 4309.1571437 (10)	total: 69.7ms	remaining: 614ms
51:	learn: 3146.2337125	test: 4498.8867985	best: 4309.1571437 (10)	total: 70.9ms	remaining: 611ms
52:	learn: 3131.5323503	test: 4498.9875506	best: 4309.1571437 (10)	total: 72ms	remaining: 607ms
53:	learn: 3094.0374355	test: 4505.3861631	best: 4309.1571437 (10)	total: 73.2ms	remaining: 605ms
54:	learn: 3050.6113636	test: 4499.8658906	best: 4309.1571437 (10)	total: 74.3ms	remaining: 601ms
55:	learn: 3030.8068625	test: 4503.1342444	best: 4309.1571437 (10)	total: 75.4ms	remaining: 598ms
56:	learn: 3001.5749306	test: 4532.3266570	best: 4309.1571437 (10)	total: 76.4ms	remaining: 594ms
57:	learn: 2977.6414199	test: 4533.0102237	best: 4309.1571437 (10)	total: 77.5ms	remaining: 591ms
58:	learn: 2965.1338264	test: 4533.1256666	best: 4309.1571437 (10)	total: 78.5ms	remaining: 587ms
59:	learn: 2946.9749543	test: 4524.5658758	best: 4309.1571437 (10)	total: 80ms	remaining: 587ms
60:	learn: 2920.6646215	test: 4535.2516986	best: 4309.1571437 (10)	total: 81.2ms	remaining: 584ms
61:	learn: 2905.1924197	test: 4540.1981921	best: 4309.1571437 (10)	total: 82.2ms	remaining: 581ms
62:	learn: 2894.8830294	test: 4537.4370051	best: 4309.1571437 (10)	total: 83.3ms	remaining: 578ms
63:	learn: 2874.0253834	test: 4540.8149824	best: 4309.1571437 (10)	total: 84.4ms	remaining: 575ms
64:	learn: 2867.5157485	test: 4543.7107471	best: 4309.1571437 (10)	total: 85.5ms	remaining: 572ms
65:	learn: 2844.0862645	test: 4562.8743236	best: 4309.1571437 (10)	total: 86.6ms	remaining: 570ms
66:	learn: 2826.1273509	test: 4565.3374245	best: 4309.1571437 (10)	total: 87.7ms	remaining: 567ms
67:	learn: 2809.0033726	test: 4575.1108849	best: 4309.1571437 (10)	total: 89ms	remaining: 566ms
68:	learn: 2799.5090858	test: 4572.9761871	best: 4309.1571437 (10)	total: 90.3ms	remaining: 564ms
69:	learn: 2784.2640122	test: 4572.7933909	best: 4309.1571437 (10)	total: 91.3ms	remaining: 561ms
70:	learn: 2765.7803170	test: 4588.9460099	best: 4309.1571437 (10)	total: 92.4ms	remaining: 558ms
71:	learn: 2758.2204638	test: 4582.8923697	best: 4309.1571437 (10)	total: 93.5ms	remaining: 556ms
72:	learn: 2741.4860925	test: 4570.1991160	best: 4309.1571437 (10)	total: 94.6ms	remaining: 553ms
73:	learn: 2736.8973668	test: 4568.0976203	best: 4309.1571437 (10)	total: 95.7ms	remaining: 551ms
74:	learn: 2725.1532422	test: 4572.7946607	best: 4309.1571437 (10)	total: 96.8ms	remaining: 549ms
75:	learn: 2703.9155860	test: 4575.2945975	best: 4309.1571437 (10)	total: 97.9ms	remaining: 546ms
76:	learn: 2687.0863878	test: 4589.1403137	best: 4309.1571437 (10)	total: 99ms	remaining: 544ms
77:	learn: 2680.5938793	test: 4597.6372399	best: 4309.1571437 (10)	total: 100ms	remaining: 542ms
78:	learn: 2672.8441793	test: 4610.3168737	best: 4309.1571437 (10)	total: 101ms	remaining: 540ms
79:	learn: 2657.2303380	test: 4623.6449327	best: 4309.1571437 (10)	total: 102ms	remaining: 537ms
80:	learn: 2637.2636377	test: 4626.9375570	best: 4309.1571437 (10)	total: 103ms	remaining: 534ms
81:	learn: 2633.1356071	test: 4630.5523116	best: 4309.1571437 (10)	total: 104ms	remaining: 532ms
82:	learn: 2624.9837343	test: 4629.8577165	best: 4309.1571437 (10)	total: 105ms	remaining: 530ms
83:	learn: 2610.3927372	test: 4633.2100386	best: 4309.1571437 (10)	total: 106ms	remaining: 527ms
84:	learn: 2593.0105335	test: 4635.3331729	best: 4309.1571437 (10)	total: 107ms	remaining: 524ms
85:	learn: 2583.0193497	test: 4636.5491243	best: 4309.1571437 (10)	total: 108ms	remaining: 522ms
86:	learn: 2570.5961833	test: 4652.0352102	best: 4309.1571437 (10)	total: 109ms	remaining: 519ms
87:	learn: 2556.4283253	test: 4650.3856224	best: 4309.1571437 (10)	total: 110ms	remaining: 516ms
88:	learn: 2538.4873018	test: 4653.1948906	best: 4309.1571437 (10)	total: 111ms	remaining: 514ms
89:	learn: 2526.8536644	test: 4659.1816036	best: 4309.1571437 (10)	total: 112ms	remaining: 511ms
90:	learn: 2497.8384174	test: 4673.5442412	best: 4309.1571437 (10)	total: 113ms	remaining: 509ms
91:	learn: 2492.5524563	test: 4673.4355852	best: 4309.1571437 (10)	total: 114ms	remaining: 507ms
92:	learn: 2481.2488990	test: 4671.8771732	best: 4309.1571437 (10)	total: 115ms	remaining: 504ms
93:	learn: 2466.7870475	test: 4672.8712235	best: 4309.1571437 (10)	total: 116ms	remaining: 502ms
94:	learn: 2453.9534739	test: 4668.2320839	best: 4309.1571437 (10)	total: 117ms	remaining: 499ms
95:	learn: 2445.1483279	test: 4669.5755395	best: 4309.1571437 (10)	total: 118ms	remaining: 497ms
96:	learn: 2426.2715101	test: 4676.8759292	best: 4309.1571437 (10)	total: 119ms	remaining: 495ms
97:	learn: 2411.3863911	test: 4675.2752155	best: 4309.1571437 (10)	total: 120ms	remaining: 493ms
98:	learn: 2393.8353649	test: 4687.1973605	best: 4309.1571437 (10)	total: 121ms	remaining: 490ms
99:	learn: 2388.7288937	test: 4690.4567809	best: 4309.1571437 (10)	total: 122ms	remaining: 488ms
100:	learn: 2370.0491809	test: 4703.4144028	best: 4309.1571437 (10)	total: 123ms	remaining: 486ms
101:	learn: 2361.3455751	test: 4704.3671635	best: 4309.1571437 (10)	total: 124ms	remaining: 484ms
102:	learn: 2350.7947009	test: 4703.2304867	best: 4309.1571437 (10)	total: 125ms	remaining: 482ms
103:	learn: 2339.6300637	test: 4724.2642205	best: 4309.1571437 (10)	total: 126ms	remaining: 479ms
104:	learn: 2327.2921182	test: 4733.0977596	best: 4309.1571437 (10)	total: 127ms	remaining: 477ms
105:	learn: 2320.2933318	test: 4731.8051002	best: 4309.1571437 (10)	total: 128ms	remaining: 476ms
106:	learn: 2312.2917834	test: 4731.6625264	best: 4309.1571437 (10)	total: 129ms	remaining: 474ms
107:	learn: 2302.8306257	test: 4747.3703463	best: 4309.1571437 (10)	total: 130ms	remaining: 472ms
108:	learn: 2288.8392383	test: 4756.0575527	best: 4309.1571437 (10)	total: 131ms	remaining: 470ms
109:	learn: 2283.2193631	test: 4756.9202303	best: 4309.1571437 (10)	total: 132ms	remaining: 468ms
110:	learn: 2262.3423966	test: 4756.5223623	best: 4309.1571437 (10)	total: 133ms	remaining: 466ms
111:	learn: 2248.3501458	test: 4756.8906464	best: 4309.1571437 (10)	total: 134ms	remaining: 464ms
112:	learn: 2234.1815002	test: 4762.7334433	best: 4309.1571437 (10)	total: 135ms	remaining: 462ms
113:	learn: 2226.6670234	test: 4764.9408246	best: 4309.1571437 (10)	total: 136ms	remaining: 460ms
114:	learn: 2218.1857666	test: 4768.1531422	best: 4309.1571437 (10)	total: 137ms	remaining: 458ms
115:	learn: 2202.8976183	test: 4777.5775546	best: 4309.1571437 (10)	total: 138ms	remaining: 456ms
116:	learn: 2195.9752151	test: 4779.2245714	best: 4309.1571437 (10)	total: 139ms	remaining: 454ms
117:	learn: 2183.1125333	test: 4788.2514683	best: 4309.1571437 (10)	total: 140ms	remaining: 453ms
118:	learn: 2173.4748181	test: 4797.5773096	best: 4309.1571437 (10)	total: 141ms	remaining: 451ms
119:	learn: 2163.4244736	test: 4813.9919148	best: 4309.1571437 (10)	total: 142ms	remaining: 449ms
120:	learn: 2155.9055955	test: 4817.7523127	best: 4309.1571437 (10)	total: 143ms	remaining: 447ms
121:	learn: 2143.6195978	test: 4811.7377753	best: 4309.1571437 (10)	total: 144ms	remaining: 445ms
122:	learn: 2131.2445711	test: 4812.0079767	best: 4309.1571437 (10)	total: 145ms	remaining: 443ms
123:	learn: 2126.1150767	test: 4823.3511689	best: 4309.1571437 (10)	total: 146ms	remaining: 441ms
124:	learn: 2104.7388498	test: 4815.3049427	best: 4309.1571437 (10)	total: 147ms	remaining: 440ms
125:	learn: 2093.6185779	test: 4808.5609504	best: 4309.1571437 (10)	total: 147ms	remaining: 438ms
126:	learn: 2079.0932134	test: 4808.2212248	best: 4309.1571437 (10)	total: 148ms	remaining: 436ms
127:	learn: 2065.3950024	test: 4808.8977320	best: 4309.1571437 (10)	total: 149ms	remaining: 434ms
128:	learn: 2055.7856018	test: 4810.1173572	best: 4309.1571437 (10)	total: 151ms	remaining: 433ms
129:	learn: 2052.0886369	test: 4811.6980299	best: 4309.1571437 (10)	total: 151ms	remaining: 431ms
130:	learn: 2037.6794821	test: 4823.5001033	best: 4309.1571437 (10)	total: 152ms	remaining: 429ms
131:	learn: 2033.6520304	test: 4826.2124670	best: 4309.1571437 (10)	total: 153ms	remaining: 428ms
132:	learn: 2030.0749801	test: 4826.2664697	best: 4309.1571437 (10)	total: 154ms	remaining: 426ms
133:	learn: 2020.7580363	test: 4829.5743589	best: 4309.1571437 (10)	total: 155ms	remaining: 424ms
134:	learn: 2011.8037520	test: 4824.7883140	best: 4309.1571437 (10)	total: 156ms	remaining: 423ms
135:	learn: 2002.3194744	test: 4823.6338727	best: 4309.1571437 (10)	total: 157ms	remaining: 421ms
136:	learn: 1994.1194614	test: 4832.1205656	best: 4309.1571437 (10)	total: 158ms	remaining: 419ms
137:	learn: 1989.6902516	test: 4832.8267949	best: 4309.1571437 (10)	total: 159ms	remaining: 418ms
138:	learn: 1978.6490035	test: 4833.8374718	best: 4309.1571437 (10)	total: 160ms	remaining: 416ms
139:	learn: 1968.7503149	test: 4831.6335629	best: 4309.1571437 (10)	total: 161ms	remaining: 414ms
140:	learn: 1962.5291785	test: 4833.7801532	best: 4309.1571437 (10)	total: 162ms	remaining: 413ms
141:	learn: 1959.0409720	test: 4831.4285889	best: 4309.1571437 (10)	total: 163ms	remaining: 411ms
142:	learn: 1933.2524742	test: 4821.5927464	best: 4309.1571437 (10)	total: 164ms	remaining: 410ms
143:	learn: 1928.1709599	test: 4830.6343856	best: 4309.1571437 (10)	total: 165ms	remaining: 408ms
144:	learn: 1924.9671377	test: 4831.9519530	best: 4309.1571437 (10)	total: 166ms	remaining: 407ms
145:	learn: 1910.8187133	test: 4835.8836351	best: 4309.1571437 (10)	total: 167ms	remaining: 405ms
146:	learn: 1906.7330596	test: 4836.1509147	best: 4309.1571437 (10)	total: 168ms	remaining: 404ms
147:	learn: 1900.6858985	test: 4836.1310386	best: 4309.1571437 (10)	total: 169ms	remaining: 402ms
148:	learn: 1894.4802828	test: 4835.0067488	best: 4309.1571437 (10)	total: 170ms	remaining: 401ms
149:	learn: 1890.3332779	test: 4834.3096262	best: 4309.1571437 (10)	total: 171ms	remaining: 399ms
150:	learn: 1884.8437248	test: 4835.3119301	best: 4309.1571437 (10)	total: 172ms	remaining: 398ms
151:	learn: 1879.3087772	test: 4835.5535565	best: 4309.1571437 (10)	total: 173ms	remaining: 396ms
152:	learn: 1876.6544505	test: 4838.7469357	best: 4309.1571437 (10)	total: 174ms	remaining: 395ms
153:	learn: 1868.3695080	test: 4845.8021421	best: 4309.1571437 (10)	total: 175ms	remaining: 393ms
154:	learn: 1858.3234929	test: 4837.3586173	best: 4309.1571437 (10)	total: 176ms	remaining: 392ms
155:	learn: 1855.3006831	test: 4836.5845308	best: 4309.1571437 (10)	total: 177ms	remaining: 390ms
156:	learn: 1846.9991687	test: 4841.3335625	best: 4309.1571437 (10)	total: 178ms	remaining: 389ms
157:	learn: 1836.6524595	test: 4849.7550367	best: 4309.1571437 (10)	total: 179ms	remaining: 388ms
158:	learn: 1834.4954101	test: 4849.8751024	best: 4309.1571437 (10)	total: 180ms	remaining: 386ms
159:	learn: 1826.8080681	test: 4850.5085308	best: 4309.1571437 (10)	total: 181ms	remaining: 385ms
160:	learn: 1819.7799764	test: 4849.6420116	best: 4309.1571437 (10)	total: 182ms	remaining: 384ms
161:	learn: 1815.5321283	test: 4848.2177409	best: 4309.1571437 (10)	total: 183ms	remaining: 382ms
162:	learn: 1812.0805271	test: 4850.2867066	best: 4309.1571437 (10)	total: 185ms	remaining: 382ms
163:	learn: 1799.2873195	test: 4857.6604084	best: 4309.1571437 (10)	total: 186ms	remaining: 381ms
164:	learn: 1796.3107623	test: 4857.4712721	best: 4309.1571437 (10)	total: 187ms	remaining: 379ms
165:	learn: 1788.3317148	test: 4856.9637669	best: 4309.1571437 (10)	total: 188ms	remaining: 378ms
166:	learn: 1784.7918439	test: 4860.8634176	best: 4309.1571437 (10)	total: 189ms	remaining: 376ms
167:	learn: 1777.3505146	test: 4856.7466150	best: 4309.1571437 (10)	total: 190ms	remaining: 375ms
168:	learn: 1771.5411103	test: 4858.6227254	best: 4309.1571437 (10)	total: 191ms	remaining: 373ms
169:	learn: 1768.4614704	test: 4864.5900225	best: 4309.1571437 (10)	total: 192ms	remaining: 372ms
170:	learn: 1763.2143328	test: 4866.7411929	best: 4309.1571437 (10)	total: 193ms	remaining: 371ms
171:	learn: 1756.6779131	test: 4866.0695679	best: 4309.1571437 (10)	total: 194ms	remaining: 369ms
172:	learn: 1751.9066405	test: 4864.3683113	best: 4309.1571437 (10)	total: 195ms	remaining: 368ms
173:	learn: 1747.3899648	test: 4862.2613572	best: 4309.1571437 (10)	total: 196ms	remaining: 367ms
174:	learn: 1743.3190823	test: 4862.1516057	best: 4309.1571437 (10)	total: 197ms	remaining: 365ms
175:	learn: 1730.4317173	test: 4861.4184584	best: 4309.1571437 (10)	total: 198ms	remaining: 364ms
176:	learn: 1722.0088351	test: 4862.9801685	best: 4309.1571437 (10)	total: 199ms	remaining: 363ms
177:	learn: 1713.2834097	test: 4862.2345552	best: 4309.1571437 (10)	total: 200ms	remaining: 362ms
178:	learn: 1704.6185290	test: 4869.3748259	best: 4309.1571437 (10)	total: 201ms	remaining: 361ms
179:	learn: 1699.6229084	test: 4869.7050500	best: 4309.1571437 (10)	total: 202ms	remaining: 360ms
180:	learn: 1694.5049442	test: 4873.0726077	best: 4309.1571437 (10)	total: 203ms	remaining: 358ms
181:	learn: 1687.4462571	test: 4878.4507619	best: 4309.1571437 (10)	total: 204ms	remaining: 357ms
182:	learn: 1682.4513778	test: 4877.9426547	best: 4309.1571437 (10)	total: 206ms	remaining: 356ms
183:	learn: 1676.4469818	test: 4873.6931617	best: 4309.1571437 (10)	total: 207ms	remaining: 355ms
184:	learn: 1671.5405801	test: 4870.9390321	best: 4309.1571437 (10)	total: 208ms	remaining: 354ms
185:	learn: 1657.4910782	test: 4872.3553385	best: 4309.1571437 (10)	total: 209ms	remaining: 353ms
186:	learn: 1655.9442395	test: 4875.1419663	best: 4309.1571437 (10)	total: 210ms	remaining: 352ms
187:	learn: 1652.0117424	test: 4875.4287449	best: 4309.1571437 (10)	total: 211ms	remaining: 350ms
188:	learn: 1647.3103188	test: 4874.1998748	best: 4309.1571437 (10)	total: 212ms	remaining: 349ms
189:	learn: 1639.7448068	test: 4875.0999978	best: 4309.1571437 (10)	total: 213ms	remaining: 348ms
190:	learn: 1632.7726717	test: 4876.1807906	best: 4309.1571437 (10)	total: 215ms	remaining: 347ms
191:	learn: 1626.7357630	test: 4875.6304466	best: 4309.1571437 (10)	total: 216ms	remaining: 346ms
192:	learn: 1621.3872969	test: 4878.1454524	best: 4309.1571437 (10)	total: 217ms	remaining: 345ms
193:	learn: 1610.8320457	test: 4885.6154297	best: 4309.1571437 (10)	total: 218ms	remaining: 344ms
194:	learn: 1603.9829700	test: 4886.3945133	best: 4309.1571437 (10)	total: 219ms	remaining: 343ms
195:	learn: 1595.2548847	test: 4887.6800598	best: 4309.1571437 (10)	total: 220ms	remaining: 342ms
196:	learn: 1591.3819693	test: 4889.5294957	best: 4309.1571437 (10)	total: 221ms	remaining: 340ms
197:	learn: 1580.5580543	test: 4898.0636819	best: 4309.1571437 (10)	total: 222ms	remaining: 339ms
198:	learn: 1575.3553731	test: 4900.6071309	best: 4309.1571437 (10)	total: 223ms	remaining: 338ms
199:	learn: 1563.5883247	test: 4903.5205050	best: 4309.1571437 (10)	total: 224ms	remaining: 336ms
200:	learn: 1556.7799096	test: 4907.0462781	best: 4309.1571437 (10)	total: 225ms	remaining: 335ms
201:	learn: 1551.8398456	test: 4902.4802230	best: 4309.1571437 (10)	total: 226ms	remaining: 334ms
202:	learn: 1542.1649476	test: 4901.4125859	best: 4309.1571437 (10)	total: 227ms	remaining: 332ms
203:	learn: 1531.9447516	test: 4900.4622724	best: 4309.1571437 (10)	total: 228ms	remaining: 331ms

### XGBoost

In [20]:
model_xg = xgb.XGBRegressor(
    n_estimators=500, 
    learning_rate = 0.5,
    max_depth = 6
)

model_xg.fit(X_train_scaled, y_train)

predications_xg = model_xg.predict(X_test_scaled)

mse_xg = mean_squared_error(y_test, predications_xg)
mae_xg = mean_absolute_error(y_test, predications_xg)
r2_xg = r2_score(y_test, predications_xg)

print(f"Среднеквадратичная ошибка (MSE): {mse_xg:.4f}")
print(f"Среднеабсолютная ошибка (MAE): {mae_xg:.4f}")
print(f"Коэффициент детерминации (R²): {r2_xg:.4f}")

Среднеквадратичная ошибка (MSE): 25210144.7632
Среднеабсолютная ошибка (MAE): 2839.4197
Коэффициент детерминации (R²): 0.8376

### LightGBM

In [21]:
lgb_model = lgb.LGBMRegressor(
    n_estimators=500, 
    learning_rate = 0.5,
    max_depth = 6
)

lgb_model.fit(X_train, y_train)

predications_lgb = lgb_model.predict(X_test)

mse_lgb = mean_squared_error(y_test, predications_lgb)
mae_lgb = mean_absolute_error(y_test, predications_lgb)
r2_lgb = r2_score(y_test, predications_lgb)

print(f"Среднеквадратичная ошибка (MSE): {mse_lgb:.4f}")
print(f"Среднеабсолютная ошибка (MAE): {mae_lgb:.4f}")
print(f"Коэффициент детерминации (R²): {r2_lgb:.4f}")

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000218 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 319
[LightGBM] [Info] Number of data points in the train set: 1070, number of used features: 8
[LightGBM] [Info] Start training from score 13346.089733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf